


import counselling_dbms.Counselling_dbms;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author d.vineeth
 */
public class AddStudentForm extends javax.swing.JFrame {
public String s ;
public static String path1 = "/Users/d.vineeth/Desktop/appointment.png";

/**
     * Creates new form AddStudentForm
     */
    
        
    public boolean checkSID( String SID){
        PreparedStatement ps4 ;
    ResultSet rs;
    boolean checksid = false;
        String query = "SELECT * FROM `Student_Details_` WHERE `SID`=?";
      
        try { 
             ps4 = Counselling_dbms.getConnection().prepareStatement(query);
            ps4.setString(1,SID);
            rs = ps4.executeQuery();
            if(rs.next()){
                checksid=true;
                
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    return checksid;
    }
     public  ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jLabel_addPhoto.getWidth(), jLabel_addPhoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    public AddStudentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel_back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_addPhoto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_StuName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_SRN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_EamR = new javax.swing.JTextField();
        jTextField_PPhN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_SBN = new javax.swing.JComboBox<>();
        jComboBox_SS = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_SPAdd = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_SPerAdd = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField_SFN = new javax.swing.JTextField();
        jTextField_SMN = new javax.swing.JTextField();
        jTextField_SMO = new javax.swing.JTextField();
        jTextField_SFO = new javax.swing.JTextField();
        jTextField_LLN = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField_SFAI = new javax.swing.JTextField();
        jTextField_MMbNo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField_SMEmailID = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField1_SFMbN = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField_SFmailID = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_SOAdd = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField_SSNa = new javax.swing.JTextField();
        jTextField_SSE = new javax.swing.JTextField();
        jTextField_SSO = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_SED = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea_CA = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea_HP = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea_G = new javax.swing.JTextArea();
        jCheckBox_A = new javax.swing.JCheckBox();
        jCheckBox_SP = new javax.swing.JCheckBox();
        jCheckBox_S = new javax.swing.JCheckBox();
        jCheckBox_EP = new javax.swing.JCheckBox();
        jCheckBox_LSE = new javax.swing.JCheckBox();
        jCheckBox_St = new javax.swing.JCheckBox();
        jCheckBox_EA = new javax.swing.JCheckBox();
        jCheckBox_NT = new javax.swing.JCheckBox();
        jCheckBox_EPh = new javax.swing.JCheckBox();
        jCheckBox_PMP = new javax.swing.JCheckBox();
        jCheckBox_PC = new javax.swing.JCheckBox();
        jCheckBox_AP = new javax.swing.JCheckBox();
        jCheckBox_C = new javax.swing.JCheckBox();
        jCheckBox_ED = new javax.swing.JCheckBox();
        jCheckBox_PDP = new javax.swing.JCheckBox();
        jCheckBox_LSC = new javax.swing.JCheckBox();
        jCheckBox_F = new javax.swing.JCheckBox();
        jCheckBox_RP = new javax.swing.JCheckBox();
        jCheckBox_MH = new javax.swing.JCheckBox();
        jCheckBox_LOE = new javax.swing.JCheckBox();
        jCheckBox_FOPS = new javax.swing.JCheckBox();
        jCheckBox_TMP = new javax.swing.JCheckBox();
        jCheckBox_LSM = new javax.swing.JCheckBox();
        jCheckBox_P = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        jButton_AddStu = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jDateChooser_DOB = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane9.setViewportView(jTextArea7);

        jScrollPane10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Class", "School/College", "Percentage", "Year of Passing"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(255, 0, 51));
        jTable2.setRowHeight(30);
        jTable2.setShowGrid(true);
        jScrollPane10.setViewportView(jTable2);

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane11.setViewportView(jTextArea8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(231, 76, 60));

        jLabel_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2_/pngkey.com-back-button-png-875502.png"))); // NOI18N
        jLabel_back.setText("  back");
        jLabel_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_backMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("FILL STUDENT DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1076, Short.MAX_VALUE)
                .addComponent(jLabel_back, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_back, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screen Shot 2019-03-04 at 12.28.41 PM.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("STUDENT INFORMATION FOR COUNSELLING");

        jPanel3.setBackground(new java.awt.Color(236, 204, 104));

        jLabel_addPhoto.setBackground(new java.awt.Color(236, 204, 104));
        jLabel_addPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default_pics/Screen Shot 2019-03-09 at 10.55.46 AM.png"))); // NOI18N
        jLabel_addPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_addPhotoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_addPhotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_addPhotoMouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(236, 204, 104));
        jLabel7.setText("  To Attach Photo CLICK BELOW");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_addPhoto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_addPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText(" * Student Name :");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("* Roll No :");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("* DOB :");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("Branch :");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Section :");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("Personal Phone No :");

        jComboBox_SBN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "IT", "MECH", "CHEM", "CIV", "EEE", "ECE", "MBA" }));

        jComboBox_SS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("* Emcet/Ecet Rank :");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("* Present Address :");

        jTextArea_SPAdd.setColumns(20);
        jTextArea_SPAdd.setRows(5);
        jScrollPane1.setViewportView(jTextArea_SPAdd);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setText("Permanent Address :");

        jTextArea_SPerAdd.setColumns(20);
        jTextArea_SPerAdd.setRows(5);
        jScrollPane2.setViewportView(jTextArea_SPerAdd);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setText("Land Line Number :");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel15.setText("* Father / Guardian's Name :");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel16.setText("* Mother's Name :");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel17.setText("Occupation :");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel18.setText("Occupation :");

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel19.setText("* Annual Income :");

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel20.setText("Mother's Mobile No :");

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel21.setText("Mother's E-Mail ID :");

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel22.setText("* Father's Mobile No :");

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel23.setText("Father's E-Mail ID : ");

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel24.setText("Address if different from above :");

        jTextArea_SOAdd.setColumns(20);
        jTextArea_SOAdd.setRows(5);
        jScrollPane3.setViewportView(jTextArea_SOAdd);

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel25.setText("Brother's / Sisters Details :");

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel26.setText("Name :");

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel27.setText("Education :");

        jLabel28.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel28.setText("Occupation :");

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel29.setText(" Education Details :");

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jTable_SED.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TENTH", null, null, null},
                {"INTER/DIPLOMA", null, null, null}
            },
            new String [] {
                "Class", "School/College", "Percentage", "Year of Passing"
            }
        ));
        jTable_SED.setGridColor(new java.awt.Color(255, 255, 51));
        jTable_SED.setRowHeight(30);
        jTable_SED.setRowSelectionAllowed(false);
        jTable_SED.setShowGrid(true);
        jScrollPane4.setViewportView(jTable_SED);

        jLabel30.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel30.setText("Sports / Cultural Activities and Interests :");

        jLabel31.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel31.setText("Health Problems If Any :");

        jLabel32.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel32.setText("Have you set any goals in your life or near future  ?  Yes/No . If Yes Explain :");

        jTextArea_CA.setColumns(20);
        jTextArea_CA.setRows(5);
        jScrollPane6.setViewportView(jTextArea_CA);

        jTextArea_HP.setColumns(20);
        jTextArea_HP.setRows(5);
        jScrollPane7.setViewportView(jTextArea_HP);

        jTextArea_G.setColumns(20);
        jTextArea_G.setRows(5);
        jScrollPane8.setViewportView(jTextArea_G);

        jCheckBox_A.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_A.setText("Anger");

        jCheckBox_SP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_SP.setText("Stage Phobia");

        jCheckBox_S.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_S.setText("Stress");

        jCheckBox_EP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_EP.setText("Emotional Problem");

        jCheckBox_LSE.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_LSE.setText("Low Self-Esteem");

        jCheckBox_St.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_St.setText("Stammering");

        jCheckBox_EA.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_EA.setText("Examination Anxiety");

        jCheckBox_NT.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_NT.setText("Negative Thoughts");

        jCheckBox_EPh.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_EPh.setText("Exam Phobia");

        jCheckBox_PMP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_PMP.setText("Poor Memory Problem");

        jCheckBox_PC.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_PC.setText("Poor Concentration");

        jCheckBox_AP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_AP.setText("Adjustment Problem");

        jCheckBox_C.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_C.setText("Conflicts");

        jCheckBox_ED.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_ED.setText("Emotional Dilemma");

        jCheckBox_PDP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_PDP.setText("Poor Decisive Power");

        jCheckBox_LSC.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_LSC.setText("Low Self Confidence");

        jCheckBox_F.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_F.setText("Frustration");

        jCheckBox_RP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_RP.setText("Relationship Problems");

        jCheckBox_MH.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_MH.setText("Migrane Headache");

        jCheckBox_LOE.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_LOE.setText("Lack of Expression");

        jCheckBox_FOPS.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_FOPS.setText("Fear of Public Speaking");

        jCheckBox_TMP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_TMP.setText("Time Management Problems");

        jCheckBox_LSM.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_LSM.setText("Low Self-Motivation");

        jCheckBox_P.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCheckBox_P.setText("Procrastination");

        jLabel33.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel33.setText("Academic / Personal Problems If Any (Please Tick Which You Have)");

        jButton_AddStu.setBackground(new java.awt.Color(123, 237, 159));
        jButton_AddStu.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton_AddStu.setText("   ADD STUDENT  ");
        jButton_AddStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AddStuMouseClicked(evt);
            }
        });

        jButton_cancel.setBackground(new java.awt.Color(255, 99, 72));
        jButton_cancel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton_cancel.setText("  Cancel");
        jButton_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_cancelMouseClicked(evt);
            }
        });

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(231, 76, 60));
        jLabel36.setText("** Make sure to fill the Starred fields before submitting form orelse form student can't be added");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel25)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                                    .addComponent(jScrollPane6)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel19)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel23)
                                                        .addComponent(jLabel22))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jLabel24))
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                            .addComponent(jLabel8)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jComboBox_SBN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel14))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(15, 15, 15)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_LLN, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jComboBox_SS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel10)
                                                    .addGap(60, 60, 60)
                                                    .addComponent(jTextField_PPhN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jTextField_StuName, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(65, 65, 65)
                                                    .addComponent(jLabel5)
                                                    .addGap(28, 28, 28)
                                                    .addComponent(jTextField_SRN, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_SFAI, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField1_SFMbN, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_SFO, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_SFmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_SFN, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane2)
                                            .addComponent(jTextField_SMN)
                                            .addComponent(jTextField_SMO)
                                            .addComponent(jTextField_MMbNo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_SMEmailID)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jTextField_EamR, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(36, 36, 36)
                                                .addComponent(jDateChooser_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel28)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_SSO))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel27)
                                                .addComponent(jLabel26))
                                            .addGap(23, 23, 23)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField_SSNa, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField_SSE, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(102, 102, 102))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_S)
                                    .addComponent(jCheckBox_NT)
                                    .addComponent(jCheckBox_A)
                                    .addComponent(jCheckBox_EP)
                                    .addComponent(jCheckBox_LSE)
                                    .addComponent(jCheckBox_EA)
                                    .addComponent(jCheckBox_EPh)
                                    .addComponent(jCheckBox_St))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_AP)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox_SP)
                                            .addComponent(jCheckBox_PC)
                                            .addComponent(jCheckBox_PMP))
                                        .addGap(133, 133, 133)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox_LOE)
                                            .addComponent(jCheckBox_TMP)
                                            .addComponent(jCheckBox_LSC)
                                            .addComponent(jCheckBox_PDP)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox_FOPS)
                                            .addComponent(jCheckBox_MH)
                                            .addComponent(jCheckBox_RP)
                                            .addComponent(jCheckBox_F))
                                        .addGap(122, 122, 122)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox_C)
                                            .addComponent(jCheckBox_LSM)
                                            .addComponent(jCheckBox_ED)
                                            .addComponent(jCheckBox_P, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(jButton_AddStu)
                        .addGap(116, 116, 116)
                        .addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_StuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_SRN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_PPhN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jComboBox_SBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox_SS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_EamR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_LLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField_SFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_SMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jTextField_SMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_SFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jTextField_MMbNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_SFAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField_SMEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField1_SFMbN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField_SFmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel25)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField_SSNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField_SSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField_SSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel29)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_S)
                    .addComponent(jCheckBox_SP)
                    .addComponent(jCheckBox_TMP))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_A)
                    .addComponent(jCheckBox_PC)
                    .addComponent(jCheckBox_LOE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_EP)
                    .addComponent(jCheckBox_PMP)
                    .addComponent(jCheckBox_LSC))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_LSE)
                    .addComponent(jCheckBox_AP)
                    .addComponent(jCheckBox_PDP))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_EA)
                    .addComponent(jCheckBox_F)
                    .addComponent(jCheckBox_C))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_NT)
                    .addComponent(jCheckBox_MH)
                    .addComponent(jCheckBox_ED))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_EPh)
                    .addComponent(jCheckBox_RP)
                    .addComponent(jCheckBox_LSM))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox_St)
                        .addComponent(jCheckBox_FOPS))
                    .addComponent(jCheckBox_P))
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AddStu)
                    .addComponent(jButton_cancel))
                .addGap(42, 42, 42)
                .addComponent(jLabel36)
                .addGap(205, 205, 205))
        );

        jScrollPane5.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 2470, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_backMouseClicked
        HOME_PAGE hp = new HOME_PAGE();
                hp.pack();
                hp.setVisible(true);
                hp.setLocationRelativeTo(null);
                hp.setExtendedState(JFrame.MAXIMIZED_BOTH);
                hp.jLabel_username.setText(" "+ Login.username +" ");
                this.dispose();
             
    }//GEN-LAST:event_jLabel_backMouseClicked

    private void jLabel_addPhotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_addPhotoMouseExited
        jPanel3.setBackground(new Color(236,204,104));
    }//GEN-LAST:event_jLabel_addPhotoMouseExited

    private void jLabel_addPhotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_addPhotoMouseEntered
        jPanel3.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_jLabel_addPhotoMouseEntered

    private void jLabel_addPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_addPhotoMouseClicked
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if(result == JFileChooser.APPROVE_OPTION){
            if (!(file.getSelectedFile().getName().endsWith(".jpg")||file.getSelectedFile().getName().endsWith(".gif")||file.getSelectedFile().getName().endsWith(".png")||file.getSelectedFile().getName().endsWith(".jpeg"))){
                JOptionPane.showMessageDialog(null,"Choose a photo in .jpg or .png or .gif formats ");
            }
            else{
                File selectedFile = file.getSelectedFile();
                s = selectedFile.getAbsolutePath();
                
                jLabel7.setVisible(false);
                jLabel_addPhoto.setIcon(ResizeImage(s));
                
            }
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            JOptionPane.showMessageDialog(null,"No photo Selected");
            
      
        }

    }//GEN-LAST:event_jLabel_addPhotoMouseClicked

    private void jButton_AddStuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AddStuMouseClicked
        
        String StuName ;
        String SID ;
        String SDOB ;
        String SBN ;
        String SS ;
        String PPhN ;
        String EamR ;
        int eamr;
        String LLN ;
        String SFN ;
        String SMN ;
        String SFO ;
        String  SMO ;
        String SFAI ;
        int sfai;
        String MMbNo;
        String SFMbN;
        String SMEmailID;
        String SFmailID;
        String SPAdd;
        String SPerAdd;
        String SOAdd;
        String SSNa;
        String SSE;
        String SSO;
        String STSN;
        String STP;
        String STYOP;
        String SCN;
        String SCP;
        String SCYOP;
String CA ;
String HP;
String G;
String S="";
String A="";
String EP="" ;
String LSE="" ;
String EA="" ;
String NT="" ;
String EPh="" ;
String St="" ;
String SP="" ;
String PC="" ;
String PMP="" ;
String AP="" ;
String F="" ;
String MH="" ;
String RP ="";
String FOPS="" ;
String TMP="" ;
String LOE="" ;
String LSC="" ;
String PDP="" ;
String ED="" ;
String C ="";
String LSM="";
String P="";
        StuName =jTextField_StuName.getText();
        if(StuName.equals("")){
            JOptionPane.showMessageDialog(null,"Student Name is Not Enterd");
        }else{
        SID =jTextField_SRN.getText();
         if ((checkSID(SID)) || (SID.equals(""))){
                JOptionPane.showMessageDialog(null,"The Student Id might not have been entered or Already Existing ");
            }else{
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    
        SDOB = dateFormat.format(jDateChooser_DOB.getDate());
        if (SDOB.equals("")){
                JOptionPane.showMessageDialog(null,"Enter Date of Birth");
        }else{
        PPhN = jTextField_PPhN.getText();
        if(PPhN.equals("")){
                    JOptionPane.showMessageDialog(null,"Enter the Personel Phone Number");
                    
                    }else{
          EamR = jTextField_EamR.getText();
        eamr = Integer.parseInt(jTextField_EamR.getText());
          if (EamR.equals("")||EamR.length()>6){
                    JOptionPane.showMessageDialog(null,"Enter a vakid Engineering Entrance Exam Rank");
                    }else{
            SPAdd = jTextArea_SPAdd.getText();
        if (SPAdd.equals("")){
                JOptionPane.showMessageDialog(null,"Enter Present Address");
            }else{
            SFN  = jTextField_SFN.getText();
        if (SFN.equals("")){
                JOptionPane.showMessageDialog(null,"Enter Student Father Name");
            }else{
            SMN = jTextField_SMN.getText();
        if (SMN.equals("")){
                JOptionPane.showMessageDialog(null,"Enter Student Mother Name");
            }else{   
        SFAI = jTextField_SFAI.getText();
        sfai = Integer.parseInt(jTextField_SFAI.getText());
        if (SFAI.equals("")){
                JOptionPane.showMessageDialog(null,"Enter Annual Income ");
            }else{
        SFMbN = jTextField1_SFMbN.getText();
        if (SFMbN.equals("")){
                JOptionPane.showMessageDialog(null,"Enter Father Mobile Number ");
            }else{
        STSN  = jTable_SED.getModel().getValueAt(0,1).toString();
        if (STSN.equals("")){
                JOptionPane.showMessageDialog(null,"Enter School Name");
            }else{
        STP = jTable_SED.getModel().getValueAt(0,2).toString();
        if (STP.equals("")){
                JOptionPane.showMessageDialog(null,"Enter Tenth percentage ");
            }else{
        STYOP = jTable_SED.getModel().getValueAt(0,3).toString();
         if (STYOP.equals("")){
                    JOptionPane.showMessageDialog(null,"Enter Tenth year of passing");  
                  }else{
        SCN = jTable_SED.getModel().getValueAt(1,1).toString();
         if ( SCN.equals("")){
                    JOptionPane.showMessageDialog(null," Enter College name ");  
                  }else{
        SCP = jTable_SED.getModel().getValueAt(1,2).toString();
        if ( SCP.equals("")){
                      JOptionPane.showMessageDialog(null,"Enter aggregate percentage in college");
                  }else{
            
        SCYOP = jTable_SED.getModel().getValueAt(1,3).toString();
        if (STYOP.equals("")){
                      JOptionPane.showMessageDialog(null,"Enter College year of passing");
                  }else{
        SMEmailID = jTextField_SMEmailID.getText();
        SFmailID = jTextField_SFmailID.getText();
        SOAdd = jTextArea_SOAdd.getText();
        SSNa = jTextField_SSNa.getText();
        SSE = jTextField_SSE.getText();
        SSO = jTextField_SSO.getText();
        SPerAdd = jTextArea_SPerAdd.getText();
        LLN = jTextField_LLN.getText();        
        SBN = jComboBox_SBN.getSelectedItem().toString();
        SS = jComboBox_SS.getSelectedItem().toString();
        SFO = jTextField_SFO.getText();
        MMbNo = jTextField_MMbNo.getText();
        SMO = jTextField_SMO.getText();
        CA = jTextArea_CA.getText();
        HP= jTextArea_HP.getText();
        G= jTextArea_G.getText();
        SMEmailID = jTextField_SMEmailID.getText();
        SFmailID = jTextField_SFmailID.getText();
        SOAdd = jTextArea_SOAdd.getText();
        SSNa = jTextField_SSNa.getText();
        SSE = jTextField_SSE.getText();
        SSO = jTextField_SSO.getText();
        SPerAdd = jTextArea_SPerAdd.getText();
        LLN = jTextField_LLN.getText();        
        SBN = jComboBox_SBN.getSelectedItem().toString();
        SS = jComboBox_SS.getSelectedItem().toString();
        SFO = jTextField_SFO.getText();
        MMbNo = jTextField_MMbNo.getText();
        SMO = jTextField_SMO.getText();
 if(jCheckBox_S.isSelected()==true){
    S +="Yes";
}
if(jCheckBox_A.isSelected()==true){
      A +="Yes";  
    }
if(jCheckBox_EP.isSelected()==true){
        EP +="Yes";
    }
if(jCheckBox_LSE.isSelected()==true){
        LSE +="Yes";
    }
if(jCheckBox_EA.isSelected()==true){
     EA +="Yes";   
    }
if(jCheckBox_NT.isSelected()==true){
     NT +="Yes";   
    }
if(jCheckBox_EPh.isSelected()==true){
     EPh +="Yes";   
    }
if(jCheckBox_St.isSelected()==true){
      St +="Yes";  
    }
if(jCheckBox_SP.isSelected()==true){
      SP +="Yes";  
    }
if(jCheckBox_PC.isSelected()==true){
     PC +="Yes";   
    }
if(jCheckBox_PMP.isSelected()==true){
       PMP +="Yes"; 
    }
if(jCheckBox_AP.isSelected()==true){
        AP +="Yes";
    }
if(jCheckBox_F.isSelected()==true){
    F +="Yes";    
    }
if(jCheckBox_MH.isSelected()==true){
     MH +="Yes";   
    }
if(jCheckBox_RP.isSelected()==true){
      RP +="RP";  
    }
if(jCheckBox_FOPS.isSelected()==true){
      FOPS +="Yes";  
    }
if(jCheckBox_TMP.isSelected()==true){
      TMP +="Yes";  
    }

 if(jCheckBox_LOE.isSelected()==true){
      LOE +="Yes";        
    }
if(jCheckBox_LSC.isSelected()==true){
       LSC +="Yes"; 
    }
if(jCheckBox_PDP.isSelected()==true){
        PDP +="Yes";
    }
       if(jCheckBox_C.isSelected()==true){
        C +="Yes";
    }
       if(jCheckBox_ED.isSelected()==true){
        ED +="Yes";
    }
       if(jCheckBox_LSM.isSelected()==true){
        LSM +="Yes";
    }
       if(jCheckBox_P.isSelected()==true){
        P +="Yes";
       }
   
        String query = "Insert into `Student_Details_`(`SID`,`C_ID`,`Student_Name`,`Student_DOB`,`Student_Branch`,`Student_Section`,`Student_Ph_No`,`EmcetOREcet_Rank`,`Present_Address`,`Permenant_address`,`Land_Line_No`,`Father_Name`,`Mother_Name`,`Father_Occupation`,`Mother_Occupation`,`Annual_Income`,`Mother_Mobile_no`,`Father_Mobile_No`,`Mother_Email`,`Father_Email`,`Other_Address`,`Student_Photo`) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
        String query2 = "Insert into `Stud_Personal_Prob_`(`SID`,`C_ID`,`Stress`,`Anger`,`Emotional_Problem`,`Low_Self_Esteem`,`Examination_Anxiety`,`Negative_Thoughts`,`Exam_Phobia`,`Stammering`,`Stage_Phobia`,`Poor_Concentration`,`Poor_Memory_Problem`,`Adjustment_Problem`,`Frustration`,`Migrane_Headache`,`Relationship_Problems`,`Fear_of_Public_Speaking`,`Time_Management_Problems`,`Lack_of_Expression`,`Low_Self_Confidence`,`Poor_Decisive_Power`,`Conflicts`,`Emotional_Dilemma`,`Low_Self_Motivation`,`Procrastination`) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
        String query3 = "Insert into `Student_OD_`(`SID`,`C_ID`,`Sibiling_Name`,`Sibiling_Education`,`Sibiling_Occupation`,`Cultural_Activities_Intrests`,`Health_Problems`,`Goals`,`School`,`College`,`Tenth_Percentage`,`Inter_Diploma_Percentage`,`Tenth_YOP`,`Inter_Diploma_YOP`) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
        
        try {
           PreparedStatement ps,ps1,ps2;
            ps = Counselling_dbms.getConnection().prepareStatement(query);
            ps1 =Counselling_dbms.getConnection().prepareStatement(query2);
            ps2=Counselling_dbms.getConnection().prepareStatement(query3);
            ps.setString(1,SID);
            ps.setString(2,Login.uiid);
            ps.setString(3,StuName);
            ps.setString(4,SDOB);
            ps.setString(5,SBN);
            ps.setString(6,SS);
            ps.setString(7,PPhN);
            ps.setInt(8,eamr);
            ps.setString(9,SPAdd);
            ps.setString(10,SPerAdd);
            ps.setString(11,LLN);
            ps.setString(12,SFN);
            ps.setString(13,SMN);
            ps.setString(14,SFO);
            ps.setString(15,SMO);
            ps.setInt(16,sfai);
            ps.setString(17,MMbNo);
            ps.setString(18,SFMbN);
            ps.setString(19,SMEmailID);
            ps.setString(20,SFmailID);
            ps.setString(21,SOAdd);
            
                    InputStream is = new FileInputStream (new File(s)) ;
                    ps.setBlob(22,is);
           ps1.setString(1,SID );
           ps1.setString(2,Login.uiid); 
           ps1.setString(3,S );
            ps1.setString(4, A);
            ps1.setString(5, EP);
            ps1.setString(6,LSE );
            ps1.setString(7, EA);
            ps1.setString(8, NT);
            ps1.setString(9, EPh);
            ps1.setString(10, St);
            ps1.setString(11, SP);
            ps1.setString(12,PC );
            ps1.setString(13, PMP);
            ps1.setString(14,AP );
            ps1.setString(15, F);
            ps1.setString(16,MH );
            ps1.setString(17, RP);
            ps1.setString(18,FOPS );
            ps1.setString(19, TMP);
            ps1.setString(20, LOE);
            ps1.setString(21, LSC);
            ps1.setString(22, PDP);
            ps1.setString(23, ED);
            ps1.setString(24,C );
            ps1.setString(25, LSM);
            ps1.setString(26,P);
            ps2.setString(1, SID);
            ps2.setString(2,Login.uiid);
            ps2.setString(3,SSNa );
            ps2.setString(4, SSE);
            ps2.setString(5, SSO);
            ps2.setString(6, CA);
            ps2.setString(7,HP );
            ps2.setString(8, G);
            ps2.setString(9,STSN );
            ps2.setString(10,SCN );
            ps2.setString(11,STP );
            ps2.setString(12, SCP);
            ps2.setString(13,STYOP );
            ps2.setString(14,SCYOP );
           if((ps.executeUpdate()>0)&&(ps1.executeUpdate()>0)&&(ps2.executeUpdate()>0)){
           ps.close();
           ps1.close();
           ps2.close();
                JOptionPane.showMessageDialog(null, "New Student Added To DataBase");
           }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "went to exception");
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }   catch (FileNotFoundException ex) {  
                Logger.getLogger(AddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            }  
        
    }//GEN-LAST:event_jButton_AddStuMouseClicked
        }
         }                                           
    }
        }
        }
        }
        }
        }
        }
        }
          }
        }
        }
         }
        }
    }
    private void jButton_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_cancelMouseClicked
        AddStudentForm lgf = new AddStudentForm() ;
        lgf.setVisible(true);
        lgf.setLocationRelativeTo(null);
        lgf.setExtendedState(JFrame.MAXIMIZED_BOTH);
        lgf.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_cancelMouseClicked



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentForm().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private javax.swing.JButton jButton_AddStu;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JCheckBox jCheckBox_A;
    private javax.swing.JCheckBox jCheckBox_AP;
    private javax.swing.JCheckBox jCheckBox_C;
    private javax.swing.JCheckBox jCheckBox_EA;
    private javax.swing.JCheckBox jCheckBox_ED;
    private javax.swing.JCheckBox jCheckBox_EP;
    private javax.swing.JCheckBox jCheckBox_EPh;
    private javax.swing.JCheckBox jCheckBox_F;
    private javax.swing.JCheckBox jCheckBox_FOPS;
    private javax.swing.JCheckBox jCheckBox_LOE;
    private javax.swing.JCheckBox jCheckBox_LSC;
    private javax.swing.JCheckBox jCheckBox_LSE;
    private javax.swing.JCheckBox jCheckBox_LSM;
    private javax.swing.JCheckBox jCheckBox_MH;
    private javax.swing.JCheckBox jCheckBox_NT;
    private javax.swing.JCheckBox jCheckBox_P;
    private javax.swing.JCheckBox jCheckBox_PC;
    private javax.swing.JCheckBox jCheckBox_PDP;
    private javax.swing.JCheckBox jCheckBox_PMP;
    private javax.swing.JCheckBox jCheckBox_RP;
    private javax.swing.JCheckBox jCheckBox_S;
    private javax.swing.JCheckBox jCheckBox_SP;
    private javax.swing.JCheckBox jCheckBox_St;
    private javax.swing.JCheckBox jCheckBox_TMP;
    private javax.swing.JComboBox<String> jComboBox_SBN;
    private javax.swing.JComboBox<String> jComboBox_SS;
    private com.toedter.calendar.JDateChooser jDateChooser_DOB;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_addPhoto;
    private javax.swing.JLabel jLabel_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable_SED;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea_CA;
    private javax.swing.JTextArea jTextArea_G;
    private javax.swing.JTextArea jTextArea_HP;
    private javax.swing.JTextArea jTextArea_SOAdd;
    private javax.swing.JTextArea jTextArea_SPAdd;
    private javax.swing.JTextArea jTextArea_SPerAdd;
    private javax.swing.JTextField jTextField1_SFMbN;
    private javax.swing.JTextField jTextField_EamR;
    private javax.swing.JTextField jTextField_LLN;
    private javax.swing.JTextField jTextField_MMbNo;
    private javax.swing.JTextField jTextField_PPhN;
    private javax.swing.JTextField jTextField_SFAI;
    private javax.swing.JTextField jTextField_SFN;
    private javax.swing.JTextField jTextField_SFO;
    private javax.swing.JTextField jTextField_SFmailID;
    private javax.swing.JTextField jTextField_SMEmailID;
    private javax.swing.JTextField jTextField_SMN;
    private javax.swing.JTextField jTextField_SMO;
    private javax.swing.JTextField jTextField_SRN;
    private javax.swing.JTextField jTextField_SSE;
    private javax.swing.JTextField jTextField_SSNa;
    private javax.swing.JTextField jTextField_SSO;
    private javax.swing.JTextField jTextField_StuName;
    // End of variables declaration//GEN-END:variables

    private JFileChooser JFileChooser() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
