

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author d.vineeth
 */
public class HOME_PAGE extends javax.swing.JFrame {

    /**
     * Creates new form HOME_PAGE
     */
    public HOME_PAGE() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel_addStudent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel_deleteStudent = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel_updateStudent = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel_searchStudent = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel_viewDetails = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panel_attendence = new java.awt.Panel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MVGR COUNSELLING SYTEM");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(231, 76, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cdb/Screen Shot 2019-03-03 at 7.41.03 PM.png"))); // NOI18N
        jLabel1.setText("LOGOUT");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel20.setText("HOME PAGE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(236, 204, 104));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("WELCOME");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("TO");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 76, 60));
        jLabel5.setText("COUNSELLING DATABASE ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel_addStudent.setBackground(new java.awt.Color(236, 204, 104));
        jPanel_addStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_addStudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_addStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_addStudentMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Add Student");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cdb/addpatient.png"))); // NOI18N
        jLabel17.setText("jLabel17");

        javax.swing.GroupLayout jPanel_addStudentLayout = new javax.swing.GroupLayout(jPanel_addStudent);
        jPanel_addStudent.setLayout(jPanel_addStudentLayout);
        jPanel_addStudentLayout.setHorizontalGroup(
            jPanel_addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addStudentLayout.createSequentialGroup()
                .addGroup(jPanel_addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_addStudentLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2))
                    .addGroup(jPanel_addStudentLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_addStudentLayout.setVerticalGroup(
            jPanel_addStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addStudentLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel_deleteStudent.setBackground(new java.awt.Color(236, 204, 104));
        jPanel_deleteStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_deleteStudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_deleteStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_deleteStudentMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText(" Delete  Student");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cdb/deletepatient.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_deleteStudentLayout = new javax.swing.GroupLayout(jPanel_deleteStudent);
        jPanel_deleteStudent.setLayout(jPanel_deleteStudentLayout);
        jPanel_deleteStudentLayout.setHorizontalGroup(
            jPanel_deleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_deleteStudentLayout.createSequentialGroup()
                .addGroup(jPanel_deleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_deleteStudentLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel11))
                    .addGroup(jPanel_deleteStudentLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel10)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel_deleteStudentLayout.setVerticalGroup(
            jPanel_deleteStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_deleteStudentLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel_updateStudent.setBackground(new java.awt.Color(236, 204, 104));
        jPanel_updateStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_updateStudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_updateStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_updateStudentMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("Update Details");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cdb/updatepatient.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_updateStudentLayout = new javax.swing.GroupLayout(jPanel_updateStudent);
        jPanel_updateStudent.setLayout(jPanel_updateStudentLayout);
        jPanel_updateStudentLayout.setHorizontalGroup(
            jPanel_updateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_updateStudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(jPanel_updateStudentLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel12)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel_updateStudentLayout.setVerticalGroup(
            jPanel_updateStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_updateStudentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel_searchStudent.setBackground(new java.awt.Color(236, 204, 104));
        jPanel_searchStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_searchStudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_searchStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_searchStudentMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setText("Search Student");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cdb/searchpatient.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_searchStudentLayout = new javax.swing.GroupLayout(jPanel_searchStudent);
        jPanel_searchStudent.setLayout(jPanel_searchStudentLayout);
        jPanel_searchStudentLayout.setHorizontalGroup(
            jPanel_searchStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_searchStudentLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(54, 54, 54))
            .addGroup(jPanel_searchStudentLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_searchStudentLayout.setVerticalGroup(
            jPanel_searchStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_searchStudentLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addGap(12, 12, 12))
        );

        jPanel_viewDetails.setBackground(new java.awt.Color(236, 204, 104));
        jPanel_viewDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_viewDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_viewDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_viewDetailsMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setText("View Details");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cdb/viewpatient.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_viewDetailsLayout = new javax.swing.GroupLayout(jPanel_viewDetails);
        jPanel_viewDetails.setLayout(jPanel_viewDetailsLayout);
        jPanel_viewDetailsLayout.setHorizontalGroup(
            jPanel_viewDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewDetailsLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel_viewDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_viewDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_viewDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(86, 86, 86))))
        );
        jPanel_viewDetailsLayout.setVerticalGroup(
            jPanel_viewDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(231, 76, 60));
        jLabel15.setText(" MAHARAJA VIJAYARAM GAJAPATHI RAJA COLLEGE OF ENGINEERING");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_cdb/Screen Shot 2019-03-03 at 10.47.50 PM.png"))); // NOI18N

        panel_attendence.setBackground(new java.awt.Color(236, 204, 104));
        panel_attendence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_attendenceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_attendenceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_attendenceMouseExited(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel19.setText(" Track Student ");

        javax.swing.GroupLayout panel_attendenceLayout = new javax.swing.GroupLayout(panel_attendence);
        panel_attendence.setLayout(panel_attendenceLayout);
        panel_attendenceLayout.setHorizontalGroup(
            panel_attendenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_attendenceLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(panel_attendenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_attendenceLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_attendenceLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(93, 93, 93))))
        );
        panel_attendenceLayout.setVerticalGroup(
            panel_attendenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_attendenceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18))
        );

        jPanel4.setBackground(new java.awt.Color(231, 76, 60));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 21)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(231, 76, 60));
        jLabel9.setText("COUNSELLER :");

        jLabel_username.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(121, 121, 121)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_addStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_searchStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel_deleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_viewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_updateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_attendence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel_deleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_updateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_searchStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_viewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_attendence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_addStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_addStudentMouseClicked
         AddStudentForm lgf = new AddStudentForm() ;
        lgf.setVisible(true);
        lgf.setLocationRelativeTo(null);
        lgf.setExtendedState(JFrame.MAXIMIZED_BOTH);
        lgf.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanel_addStudentMouseClicked

    private void jPanel_deleteStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_deleteStudentMouseClicked
        DeleteStudent del = new DeleteStudent();
         del.setVisible(true);
        del.setLocationRelativeTo(null);
        del.setExtendedState(JFrame.MAXIMIZED_BOTH);
        del.setDefaultCloseOperation(EXIT_ON_CLOSE);
        DeleteStudent.Show_Students_Id_JTable_();
        this.dispose();
    }//GEN-LAST:event_jPanel_deleteStudentMouseClicked

    private void jPanel_updateStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_updateStudentMouseClicked
        UpdateStudent upd = new UpdateStudent(); 
        upd.setVisible(true);
        upd.setLocationRelativeTo(null);
        upd.setExtendedState(JFrame.MAXIMIZED_BOTH);
        upd.setDefaultCloseOperation(EXIT_ON_CLOSE);
        UpdateStudent.Show_Students_Id_JTable_();
        this.dispose();
    }//GEN-LAST:event_jPanel_updateStudentMouseClicked

    private void jPanel_searchStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_searchStudentMouseClicked
        SearchStudent sst = new SearchStudent();
         sst.setVisible(true);
        sst.setLocationRelativeTo(null);
        sst.setExtendedState(JFrame.MAXIMIZED_BOTH);
        sst.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanel_searchStudentMouseClicked

    private void jPanel_viewDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_viewDetailsMouseClicked
       
        ViewDetails vdt = new ViewDetails();
        vdt.pack();
        vdt.setVisible(true);
        vdt.setLocationRelativeTo(null);
        vdt.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ViewDetails.Get_Student_ID_List();
        ViewDetails.Show_Students_Id_JTable();
        this.dispose();
    }//GEN-LAST:event_jPanel_viewDetailsMouseClicked

    private void jPanel_addStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_addStudentMouseEntered
        jPanel_addStudent.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_jPanel_addStudentMouseEntered

    private void jPanel_addStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_addStudentMouseExited
        jPanel_addStudent.setBackground(new Color(236,204,104));
    }//GEN-LAST:event_jPanel_addStudentMouseExited

    private void jPanel_deleteStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_deleteStudentMouseEntered
         jPanel_deleteStudent.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_jPanel_deleteStudentMouseEntered

    private void jPanel_deleteStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_deleteStudentMouseExited
        jPanel_deleteStudent.setBackground(new Color(236,204,104));
    }//GEN-LAST:event_jPanel_deleteStudentMouseExited

    private void jPanel_updateStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_updateStudentMouseEntered
        jPanel_updateStudent.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_jPanel_updateStudentMouseEntered

    private void jPanel_updateStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_updateStudentMouseExited
         jPanel_updateStudent.setBackground(new Color(236,204,104));
    }//GEN-LAST:event_jPanel_updateStudentMouseExited

    private void jPanel_searchStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_searchStudentMouseEntered
        jPanel_searchStudent.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_jPanel_searchStudentMouseEntered

    private void jPanel_searchStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_searchStudentMouseExited
         jPanel_searchStudent.setBackground(new Color(236,204,104));
    }//GEN-LAST:event_jPanel_searchStudentMouseExited

    private void jPanel_viewDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_viewDetailsMouseEntered
        jPanel_viewDetails.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_jPanel_viewDetailsMouseEntered

    private void jPanel_viewDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_viewDetailsMouseExited
         jPanel_viewDetails.setBackground(new Color(236,204,104));
    }//GEN-LAST:event_jPanel_viewDetailsMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Login lp = new Login();
                lp.setVisible(true);
                lp.pack();
                lp.setLocationRelativeTo(null);
                this.dispose();
                
    }//GEN-LAST:event_jLabel1MouseClicked

    private void panel_attendenceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_attendenceMouseEntered
        panel_attendence.setBackground(new Color(231,76,60));
    }//GEN-LAST:event_panel_attendenceMouseEntered

    private void panel_attendenceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_attendenceMouseExited
        panel_attendence.setBackground(new Color(236,204,104));
    }//GEN-LAST:event_panel_attendenceMouseExited

    private void panel_attendenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_attendenceMouseClicked
        TrackStudent tst = new TrackStudent();
         tst.setVisible(true);
        tst.setLocationRelativeTo(null);
        tst.setExtendedState(JFrame.MAXIMIZED_BOTH);
        tst.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_panel_attendenceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME_PAGE().setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_addStudent;
    private javax.swing.JPanel jPanel_deleteStudent;
    private javax.swing.JPanel jPanel_searchStudent;
    private javax.swing.JPanel jPanel_updateStudent;
    private javax.swing.JPanel jPanel_viewDetails;
    private java.awt.Panel panel_attendence;
    // End of variables declaration//GEN-END:variables
}
